### ISSUE TITLE
Skanderbeg Square

### ISSUE THREAD

**Issue by debatik** [Debatikcenter/debatikcenter#10]
6. Re: "Skanderbeg Suqare" - the general text in this rubric, and the explanatory texts under each of the individual works included in this rubric, should be aligned with the outer edges of the image/s.
7. Also re: Skanderbeg Square - The arrows leading from one work to the next should be much smaller than they currently are and they should be positioned under the photos/videos on the bottom right corner.

**Comment by sidorelauku** [comment]
Menu style is updated, now it doesn't crop when hover. Also images & text are aligned as with home page. Working with other detalis now.

**Comment by ArmandoLulaj** [comment]
Yes, you can add "kutine me katrore te vegjel qe te kthen tek faqja kryesore scanderbeg square"

**Comment by ArmandoLulaj** [comment]
Plus the arrows should allow you to go from the first photo to the last one and backwards.

**Comment by ArmandoLulaj** [comment]
Pissed Off should be smaller, the same size with Ardit Gjoklaj's photo and Naming the Halter video. Text and Caption also similar for the three pages.

**Comment by sidorelauku** [comment]
Images updated with new one's. Also centered and resized on a format. 
While I still have to work a bit with videos as height is not set yet same as images.

@debatik  should the text below be aligned as outer edges of the image, or inline with menu?

**Comment by ArmandoLulaj** [comment]
Imazhet te puneve tek "Skanderbeg Square" jane tashme te centruara dhe shigjetat funksionojn. Perfekt!

Per t'u bere akoma:

Te gjitha imazhet, pra foto + video, duhet te zmadhohen me 1 cm nga te gjitha anet, pra lart, poshte, majtas, djathtas.
Persa i perket lartesise, imazhet foto jane gati katrore kurse imazhet video jane drejtkendore, keshtuqe nuk do te jene kurre njesoj. Kjo nuk duhet te ndryshoje. Pra si reference per imazhet do te marrim gjeresine dhe jo gjatesine.
Teksti "Autor, Titull, Vit" ne cdo rast duhet te vendoset nen imazhin, foto apo video, duke filluar nga bordura e majte e imazhit.
Shigjetat majtas-djathtas duhet te vendosen gjithashtu nen imazhin, foto apo video, por ne skajin e djathte te imazhit.

**Comment by ArmandoLulaj** [comment]
Last point, and in answer to your comment above, YES, the texts below the works in "Skanderbeg Square" should be aligned with the outer edges of the images, both photo and video. Thanks!

**Comment by JonidaG** [comment]
To give you an idea about how the text and the arrows should look like in relation to the images:
![screen shot 2018-03-15 at 12 16 39 pm](https://user-images.githubusercontent.com/37385620/37474799-86110530-2871-11e8-8478-c87a58e73b15.jpg)

**Comment by JonidaG** [comment]
This goes not only for "Skanderbeg Square", but also same for the texts accompanying the images, photo + video, the other rubrics under "strikes", as illustrated below:
![screen shot 2018-03-15 at 5 00 04 pm](https://user-images.githubusercontent.com/37385620/37475441-0729f428-2873-11e8-84d2-1357fdc99f5e.jpg)

**Comment by JonidaG** [comment]
Finally, if you look at the "Skanderbeg Square" page where all three works appear together, the three images should also be in the centre of the page. Similarly, the text below should be aligned with the outer edge of the image on the left and the outer edge of the image on the right. See below:
![screen shot 2018-03-15 at 4 57 00 pm](https://user-images.githubusercontent.com/37385620/37475886-0c565f30-2874-11e8-846f-a4970fc8c142.jpg)

**Comment by sidorelauku** [comment]
I updated the link for pissed off image here: http://debatikcenter.net/strikes/image1.html
Is it ok?

**Comment by JonidaG** [comment]
Looking awesome @sidorelauku! Same needs to be done for "Naming the Halter..." and "Untitled" :)

**Comment by sidorelauku** [comment]
On it right now :)

**Comment by sidorelauku** [comment]
Changes are made for all the pages under strikes: "Naming the Halter .. ", "Untitled", "breaking stones", "reassemble" and "gaza gaze".

Should the footer be present n each of those pages?

**Comment by JonidaG** [comment]
That's fantastic @sidorelauku! I have just one observation though: In every case the line with the name of the author, title of the work, and year of production of the work should be placed at a fixed distance from the lower edge of the photo above it and the first line of text below it. I do not mean that these two distances should be the same, they should not, but that they should be fixed for all of the works under "strikes". So, for example, the distance between the line "Pleurad Xhafa, Untitled, 2017" and the border of the photo above it should be exactly the same as the distance between the line "Armando Lulaj, Pissed Off, 2017" and the border of the photo above it. Similarly, the distance between "Pleurad Xhafa, Untitled, 2017" and the first line of text below it should be exactly the same as the distance between "Armando Lulaj, Pissed Off, 2017" and the first line of text below it.

**Comment by sidorelauku** [comment]
Completed.
