### ISSUE TITLE
Texts

### ISSUE THREAD

**Issue by debatik** [Debatikcenter/debatikcenter#12]
All texts must be justified, whichever rubric they're in. 
10.Text size for all rubrics should be regular 11.5  Arial Narrow following the design we already decided. 
11. All names and titles of works should be regular 12.5  Arial Narrow following the design we already have. 
12. The font for the names of the headings, i.e., "home", "strike", etc., and subheadings, i.e., "skanderbeg square", etc., is work sans size 10.

**Comment by sidorelauku** [comment]
> 10.Text size for all rubrics should be regular 11.5 Arial Narrow following the design we already decided.

This is done now, can you please check if I applied the right font & size.

> 11. All names and titles of works should be regular 12.5 Arial Narrow following the design we already have.

I will have a look tomorrow. Is this only for names of people or also for places?

> 12. The font for the names of the headings, i.e., "home", "strike", etc., and subheadings, i.e., "skanderbeg square", etc., is work sans size 

Work in progess, will be applied tomorrow.

**Comment by JonidaG** [comment]
10.Text size for all rubrics should be regular 11.5 Arial Narrow following the design we already decided.

This is done now, can you please check if I applied the right font & size. - YES IT IS.

11.All names and titles of works should be regular 12.5 Arial Narrow following the design we already have.

I will have a look tomorrow. Is this only for names of people or also for places? - THIS IS ONLY FOR THE ARTWORKS, SO THE TEXT LINE "ARTIST, TITLE, YEAR" THAT APPEARS UNDERNEATH THE WORKS IN "SKANDERBEG SQUARE", AS WELL AS "BREAKING STONES", "REASSEMBLE", AND "GAZA GAZE". THE DIRECTIONS DO ***NOT*** APPLY  TO THE NAMES OF PEOPLE AND/OR PLACES IN GENERAL.

**Comment by ArmandoLulaj** [comment]
please read e-mail
