### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by debatik** [Debatikcenter/debatikcenter#15]
15. Home pg bottom left should be added a small size text: Copyright DEBATIKCENTER of Contemporary Art. 
16. Home pg bottom right should be added a small size text: info.debatikcenter@gmail.com

**Comment by silvaarapi** [comment]
The info was added: http://debatikcenter.net/

**Comment by ArmandoLulaj** [comment]
please do substitute the footers using these specifications: 
Font Consolas, regular 10.5 for the first line of the following text and 10 for the 2nd line. 
Instead of Debatikcenter of Contemporary Art put these 2 lines together exactly like this. 

© DCCA. ALL RIGHTS RESERVED
  info.debatikcenter@gmail.com

**Comment by ArmandoLulaj** [comment]
Note: the two infos should be justified.

**Comment by sidorelauku** [comment]
Footer is now updated on main page, when hover email changes color to white.. If you are ok with changes
, can we proceed with it?

**Comment by ArmandoLulaj** [comment]
Perfect!  
just one thing: can you make a bit smaller the first footer?  The same length as the e-mail address.

**Comment by ArmandoLulaj** [comment]
and also between ©  and DCCA should be more space and shouldn't appear linked like they are now: ©DCCA. ALL RIGHTS RESERVED but like this  ©  DCCA. ALL RIGHTS RESERVED

**Comment by sidorelauku** [comment]
@ArmandoLulaj The space is added and font-size changed.
Is the postion ok? Should we move it a bit to create space at bottom or in the left?

**Comment by ArmandoLulaj** [comment]
Yes move it a bit. Correct.

**Comment by ArmandoLulaj** [comment]
there is a mistake: the e-mail address is: info.debatikcenter@gmail.com 
NOT
info@debatikcenter.com

**Comment by ArmandoLulaj** [comment]
Regarding the position it aligned with the logo on the left.

**Comment by ArmandoLulaj** [comment]
Regarding the position it should be aligned with the logo on the left.

**Comment by sidorelauku** [comment]
Changed alignment and corrected the mistake with email.
