### ISSUE TITLE
Arrows for slideshow of images

### ISSUE THREAD

**Issue by rskikuli** [Debatikcenter/debatikcenter#16]
Here is an example of how it needs to be done: https://www.lissongallery.com/artists/marina-abramovic. 

Kliko tek shigjetat e imazhit dhe shiko sesi del dritarja gri e cila eshte gjithje njesoj por imazhet ndryshojne madhesi sipas rastit, permasa + format. 
Mund ta zgjidhim keshtu problemin me madhesine e dritares gri dhe teksti do te jete gjithnje i sakte.

**Comment by debatik** [comment]
Shembulli i lissongallery eshte shume ok, vetem po mendoja nese katrorin gri ta benim te padukshem.

**Comment by sidorelauku** [comment]
Shigjetat u ndryshuan tek imazhet, tashme jane me te vogla dhe nen imazhe. Persa i perket hapesires gri (qe mund te jete e padukshme) ceshtja eshte nese imazhi duhet te jete me ne qender apo te filloje ne nje vije me fjalen "home"?

**Comment by debatik** [comment]
Po, imazhi duhet te jete ne qender dhe pak me i vogel duke ju referuar imazhit  "Pissed off" duke u vendosur imazhi ne qender fjala home supozohet te spostohet me djathtas. Po keshtu me kete linje do te vazhdohet me te gjitha imazhet e tjera dhe vidjot. Edhe teksti do te kete ne nje linje me foton. Hapsira gri do te sherbeje nese fotografija mund te jete me e ngushte. ( kjo mund te sherbeje ne te ardhmen per fotografi te cilat nuk jane njesoj si madhesi) Ajo prape do te rrije ne qender megjithese eshte me e ngushte.

**Comment by debatik** [comment]
Mund te fillojme nga kjo per ta vendosur ne qender.

![1](https://user-images.githubusercontent.com/37342120/37368153-b50d8128-2705-11e8-837f-34dd04e48a10.jpg)

**Comment by sidorelauku** [comment]
Kjo eshte ajo qe kuptova une. Eshte ne rregull per te vazhduar keshtu?

![screenshot image strikes](https://user-images.githubusercontent.com/24439184/37407090-28aec4b4-2799-11e8-9fd6-294071b1129b.png)

**Comment by ArmandoLulaj** [comment]
Adi do te pergjigjet ne me hollesi, por shkurtimisht: duhet te centrohet, pra te vihet ne qender te faqes, vetem imazhi/video, kurse menu bar duhet te rrije aty ku ishte!

**Comment by ArmandoLulaj** [comment]
Pra, ne shembullin me larte, imazhi eshte shume mire pasi eshte i centruar, kurse menu bar duhet spostuar majtas aty ku ishte. Nderkaq, "Armando Lulaj, Pissed Off, 2017" si dhe shigjetat majtas-djathtas duhet te dalin poshte fotografise.

**Comment by ArmandoLulaj** [comment]
Gjithmone duke iu referuar shembullit te mesiperm, pra Pissed Off, a mund ta zmadhojme fotografine me rretj 1cm nga te gjitha anet? Pra lart, poshte, majtas dhe djathtas. Keto permasa mund t'i perdorim me pas si reference per te gjitha fotot/video-t qe kemi per momentin si dhe ato qe do te shtohen me vone.

**Comment by sidorelauku** [comment]
Levizja me shigjetat te imazheve te scanderbeg square eshte ne rregull tashme. Imazhet dhe videot jane te centuara. Duhet vetem te rregullohet imazhi i tek videot, qe te shfaqen me mire dhe height i videos nuk eshte i njejte me imazhet akoma.

**Comment by sidorelauku** [comment]
Po e mbyll kete issue pasi shigjetat funksionojne sipas kerkesave te mesiperme.
