### ISSUE TITLE
Menu bar and logo

### ISSUE THREAD

**Issue by ArmandoLulaj** [Debatikcenter/debatikcenter#17]
The logo is not correctly aligned with the menu bar, so the position of the logo in relation to the menu bar changes depending on the rubric you're looking at. Needless to say, the logo must always appear in the exact same spot in relation to the menu bar.

Also, the menu bar itself must always be in the same exact position no matter what page you're looking at. At the moment, the distance between the menu bar and the borders above and to the left changes slightly depending on which rubric you're looking at.

**Comment by sidorelauku** [comment]
LOgo and menu is aligned. Will close the issue.
