### ISSUE TITLE
Moving billboard category

### ISSUE THREAD

**Issue by rskikuli** [Debatikcenter/debatikcenter#25]
Adding content based on the design send by @Pleurad. Please @Pleurad upload material on this issue. 
Thanks.

**Comment by rskikuli** [comment]
![1- layout shembull i plote](https://user-images.githubusercontent.com/17770262/40583961-170f5392-6199-11e8-803d-ad35927aaa66.jpg)
![2- layout shembull scroll](https://user-images.githubusercontent.com/17770262/40583962-1735c022-6199-11e8-9545-67397bc8bd41.jpg)
![3- layout shembull foto](https://user-images.githubusercontent.com/17770262/40583963-1757d90a-6199-11e8-8ab7-34074fb308e0.jpg)
![4- shembull foto](https://user-images.githubusercontent.com/17770262/40583964-177a8482-6199-11e8-97be-bb75447875b9.jpg)
![evidence](https://user-images.githubusercontent.com/17770262/40583965-179c152a-6199-11e8-8e68-c0776ede2a3f.jpg)
Materials needed to use on this page.

**Comment by sidorelauku** [comment]
Layout is created will work on the next days to make black boxes retangular and add more space between them.

I think is also the time to add the first image.
