### ISSUE TITLE
Footer: add info

### ISSUE THREAD

**Issue by rskikuli** [Debatikcenter/debatikcenter#3]
We should add the contact (info.debatikcenter@gmail.com with a mailto: command) and the credits with a backlink to www.collective68.tech.

**Comment by rskikuli** [comment]
Also I would propose to add a 'improve this website' text that links to the GitHub repo.

**Comment by silvaarapi** [comment]
I created a simple footer for this page: http://debatikcenter.net/strikes/skanderbeg_square.html

Check it for additional changes so we can add it later in the other pages too.

**Comment by rskikuli** [comment]
Some of the text from the page is cut due to the implementation of the footer. Please check again @silvaarapi. More comments: 

- grey text;
- smaller fonts;
- the love sign should not be an image but  text <3;

**Comment by debatik** [comment]
Home pg bottom left should be added a small size text: Copyright DEBATIKCENTER of Contemporary Art.
    Home pg bottom right should be added a small size text: info.debatikcenter@gmail.com

**Comment by ArmandoLulaj** [comment]
please read e-mail

**Comment by sidorelauku** [comment]
Footer needs to be aligned on all the pages with the same style. Deadline 1.04.2018

**Comment by sidorelauku** [comment]
first line 8.8 pt
second line 8.5 pt;

**Comment by sidorelauku** [comment]
Team suggested to have footer only interested the main page, including also social icons on the right end. 
Font is changed to Overpass Mono which is open source.
