### ISSUE TITLE
Image size to be reduced

### ISSUE THREAD

**Issue by rskikuli** [Debatikcenter/debatikcenter#6]
On almost all pages the images are quite big and take a long time to load. Let's make the images with a smaller size but with the same good quality of the image starting from this one: http://debatikcenter.net/strikes/skanderbeg_square.html.

**Comment by ArmandoLulaj** [comment]
do you need images to be resized with photoshop? we can do this so we can save time.

**Comment by sidorelauku** [comment]
Yes it would help me if you do so. 
Also If I understood it right, now images should be centered?

**Comment by ArmandoLulaj** [comment]
Adi will give a hint on this. He followed better than me this issue.

**Comment by ArmandoLulaj** [comment]
Any particular size for the images?

**Comment by ArmandoLulaj** [comment]
images we are using are 1920x680.

**Comment by debatik** [comment]
Po Sidorela, fotografite tek "skenderbeg square" duhet te vendosen ne qender po ashtu dhe vidjo. gjithashtu fotot te jene disi me te vogla se aktualisht. Dicka tjeter qe po vija re eshte kur leviz me shigjetat ne te djathte fotografia e Artidit Gjoklajt nuk del. Ajo del kur leviz vetem me shigjeten e majt.

**Comment by sidorelauku** [comment]
I think to find an appropriate size you want to be on page, Reassemble video has a width 760 px. Can you resize images 760 px width?
Here is an example I changed: http://debatikcenter.net/strikes/image1.html
Is this right?

**Comment by debatik** [comment]
Ndryshimi i fotos "Pissed off" i vendosur ne qender eshte shume ok. Mund te provosh ta zmadhosh edhe pak? Nga 1 cm si ne krahun e djathte edhe ne te majtin. Titulli i fotografise do te qendroje poshte ne vijen paralele me fillimin e fotos. Edhe shigjetat do te qendrojne posht ne vijen paralele me fundin e fotos. Teksti po ashtu to do filloje dhe mbaroje ne skajet paralele te fotografise. Kete permase te fotos  do ta kemi  si shembull mates per ta ndjekur ne te gjitha fotot, vidjot dhe tekstet. 
P.s mendojme qe dritaret mos te levizin ne qender por te qendrojne aty ku ndodhen aktualisht.

**Comment by debatik** [comment]
Te gjitha fotografite te duhen 760px edhe ato qe jane fit to page?

**Comment by ArmandoLulaj** [comment]
Images were sent by Adi via e-mail.

**Comment by ArmandoLulaj** [comment]
Imazhet te puneve tek "Skanderbeg Square" jane tashme te centruara dhe shigjetat funksionojn. Perfekt!

Per t'u bere akoma:

1. Te gjitha imazhet, pra foto + video, duhet te zmadhohen me 1 cm nga te gjitha anet, pra lart, poshte, majtas, djathtas.
2. Persa i perket lartesise, imazhet foto jane gati katrore kurse imazhet video jane drejtkendore, keshtuqe nuk do te jene kurre njesoj. Kjo nuk duhet te ndryshoje. Pra si reference per imazhet do te marrim gjeresine dhe jo gjatesine.
3. Teksti "Autor, Titull, Vit" ne cdo rast duhet te vendoset nen imazhin, foto apo video, duke filluar nga bordura e majte e imazhit.
4. Shigjetat majtas-djathtas duhet te vendosen gjithashtu nen imazhin, foto apo video, por ne skajin e djathte te imazhit.
