### ISSUE TITLE
strikes and others

### ISSUE THREAD

**Issue by debatik** [Debatikcenter/debatikcenter#8]
1. All photos, videos, and texts should be positioned exactly in the middle of the page.
2. All photos, videos, and texts should be aligned with the outer edge of the "home" button on the left hand side.
3. The distance between all photos, videos, and texts and the headings above them, i.e., "home", "strikes", "texts", "archive", "black sun projects", and "surveillance", should be fixed.

**Comment by ArmandoLulaj** [comment]
All photos, videos, and texts should be positioned exactly in the middle of the page. (DONE) 
The distance between all photos, videos, and texts and the headings above them, i.e., "home", "strikes", "texts", "archive", "black sun projects", and "surveillance", should be fixed.

**Comment by ArmandoLulaj** [comment]
Imazhet te puneve tek "Skanderbeg Square" jane tashme te centruara dhe shigjetat funksionojn. Perfekt!

Per t'u bere akoma:

Te gjitha imazhet, pra foto + video, duhet te zmadhohen me 1 cm nga te gjitha anet, pra lart, poshte, majtas, djathtas.
Persa i perket lartesise, imazhet foto jane gati katrore kurse imazhet video jane drejtkendore, keshtuqe nuk do te jene kurre njesoj. Kjo nuk duhet te ndryshoje. Pra si reference per imazhet do te marrim gjeresine dhe jo gjatesine.
Teksti "Autor, Titull, Vit" ne cdo rast duhet te vendoset nen imazhin, foto apo video, duke filluar nga bordura e majte e imazhit.
Shigjetat majtas-djathtas duhet te vendosen gjithashtu nen imazhin, foto apo video, por ne skajin e djathte te imazhit.

**Comment by sidorelauku** [comment]
Te gjitha fotot dhe videot jane zmadhuar. Si duken tani? Mendoni ti leme ne kete madhesi?
Teksti nen foton dhe videon eshte justified  ne kolone. Shigjetat nen foto/video ne te njejtin drejtim me titullin e fotos/videos.

**Comment by JonidaG** [comment]
That's fantastic @sidorelauku! I have just one observation though: In every case the line with the name of the author, title of the work, and year of production of the work should be placed at a fixed distance from the lower edge of the photo above it and the first line of text below it. I do not mean that these two distances should be the same, they should not, but that they should be fixed for all of the works under "strikes". So, for example, the distance between the line "Pleurad Xhafa, Untitled, 2017" and the border of the photo above it should be exactly the same as the distance between the line "Armando Lulaj, Pissed Off, 2017" and the border of the photo above it. Similarly, the distance between "Pleurad Xhafa, Untitled, 2017" and the first line of text below it should be exactly the same as the distance between "Armando Lulaj, Pissed Off, 2017" and the first line of text below it.

**Comment by sidorelauku** [comment]
The distance between the title and the photo is now bigger than the distance between title and the first line of text below it. Have a look if you agree this way or should I change something?
Those distances are applied to all the pages under strikes with the same metrics.
